#!/usr/bin/python

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import json, os, time, sys, getpass


def create_repo(username, password, repo_name, is_private, repo_path="."):

    driver = webdriver.Chrome("./chromedriver")
    driver.get("http://www.github.com")
    driver.set_window_size(1500, 1000)


    # go to sign in screen
    go_to_sign_in_button = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/div[2]/a[1]")
    go_to_sign_in_button.click()

    username_input_element = driver.find_element_by_xpath('//*[@id="login_field"]')
    password_input_element = driver.find_element_by_xpath('//*[@id="password"]')
    sign_in_button         = driver.find_element_by_xpath('//*[@id="login"]/form/div[4]/input[9]')

    username_input_element.send_keys(username)
    password_input_element.send_keys(password)
    sign_in_button.click()

    # go to new repo window
    new_repo_button = driver.find_element_by_xpath("/html/body/div[4]/div/aside[1]/div[2]/div[1]/div/h2/a")
    new_repo_button.click()

    # enter repo infos and create repo
    repo_name_input_element = driver.find_element_by_xpath('//*[@id="repository_name"]')
    repo_name_input_element.send_keys(repo_name)

    if is_private:
        is_private_checkbox_element = driver.find_element_by_xpath('//*[@id="repository_visibility_private"]')
        is_private_checkbox_element.click()

    time.sleep(1.5)
    create_repo_button = driver.find_element_by_xpath('//*[@id="new_repository"]/div[3]/button')
    # create_repo_button.click()

    # close browser
    driver.close()

    # execute all commands
    commands = [
        'mkdir -p %s/%s' % (repo_path, repo_name),
        'cd %s/%s' % (repo_path, repo_name),
        'git init',
        'echo "%s" >> README.md' % repo_name,
        'git add README.md',
        'git commit -m "first commit"',
        'git remote add origin https://github.com/%s/%s.git' % (username, repo_name),
        'git push -u origin master'
    ]

    os.system(" && ".join(commands))


if __name__ == "__main__":
    username    = None
    password    = None
    repo_name   = None
    repo_path   = None
    is_private  = None

    # inputs must be non-empty
    while not username:
        username =  raw_input("username > ")

    while not password:
        password =  getpass.getpass(prompt="password > ", stream=None)

    while not repo_name:
        repo_name =  raw_input("repo_name > ")

    while not repo_path:
        repo_path =  raw_input("repo_path > ")
    # path must not end with '/'
    if repo_path != '/':
        repo_path = repo_path.rstrip('/')

    while not is_private in ['y', 'n']:
        is_private  =  raw_input("is_private (y/n) > ")

    create_repo(
        username,
        password,
        repo_name,
        is_private,
        repo_path
    )
    